<%@ page contentType="text/html;charset=UTF-8" %>
<!DOCTYPE html>
<html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>InversorAR</title><link rel="stylesheet" href="<%= request.getContextPath() %>/assets/dashboard.css"></head>
<body><header><div class="brand"><span>✓</span> InversorAR</div><nav>Dashboard　 Portfolio　 Rendimiento　 Historial　 Simulador</nav><div class="acciones"><button id="abrirModal" disabled>＋ Comprar</button><button id="abrirModalVenta" class="vender" disabled>− Vender</button></div></header>
<main><h1>Mi Portfolio</h1><p class="sub" id="origen">Cargando…</p><section class="metricas"><article><small>CAPITAL INVERTIDO</small><strong id="capital">—</strong></article><article><small>PATRIMONIO TOTAL</small><strong id="patrimonio">—</strong></article><article><small>GANANCIA TOTAL</small><strong id="ganancia">—</strong></article></section>
<section class="panel"><h2>Mis inversiones</h2><div id="posiciones" class="posiciones"><p>Cargando inversiones…</p></div></section>
</main>
<dialog id="catalogoPanel" class="panel catalogo" aria-labelledby="tituloCatalogo"><div class="modalTitulo"><h2 id="tituloCatalogo">Elegí un instrumento</h2><button id="cerrarCatalogo" class="cerrar" aria-label="Cerrar catálogo">×</button></div><p class="aviso">Precios históricos de la base compartida. Los instrumentos sin precio o sin moneda identificada se pueden consultar, pero no comprar.</p>
<form id="busquedaCatalogo" class="buscador"><label>Nombre o símbolo<input id="buscar" maxlength="80" placeholder="BTCUSDT, Ethereum…"></label><button class="secundario">Buscar</button></form>
<p id="catalogoError" class="error" role="alert"></p><div class="tabla"><table><thead><tr><th>Instrumento</th><th>Último cierre</th><th>Acciones</th></tr></thead><tbody id="catalogoFilas"></tbody></table></div>
<div class="paginacion"><button id="anterior" class="secundario">Anterior</button><span id="pagina"></span><button id="siguiente" class="secundario">Siguiente</button></div></dialog>
<dialog id="historial"><div class="modalTitulo"><h2 id="tituloHistorial">Historial</h2><button id="cerrarHistorial" class="cerrar" aria-label="Cerrar historial">×</button></div><p class="aviso">Hasta 90 registros, del más reciente al más antiguo.</p><div class="tabla"><table><thead><tr><th>Fecha</th><th>Cierre</th><th>Volumen</th></tr></thead><tbody id="historialFilas"></tbody></table></div></dialog>
<dialog id="modal"><form id="formCompra"><div class="modalTitulo"><h2>Comprar instrumento</h2><button type="button" id="cerrarModal" class="cerrar">×</button></div><label>Tipo de instrumento<select id="tipoInstrumento"><option value="">Todos los tipos</option><option value="ACCION">Acciones</option><option value="BONO">Bonos</option><option value="CEDEAR">CEDEARs</option><option value="CRIPTO">Criptomonedas</option><option value="MONEDA">Monedas</option></select></label><label>Instrumento<select id="instrumento" required><option value="">Seleccioná un instrumento…</option></select></label><p id="disponibilidadTipo" class="sub" role="status"></p><button type="button" id="abrirCatalogo" class="enlace" hidden>Consultar precios e historial</button><div class="dos"><label>Ticker<input id="ticker" readonly></label><label>Cantidad<input id="cantidad" type="number" min="0" step="any" required></label></div><div class="dos"><label>Precio por unidad <span id="monedaCompra"></span><input id="precio" type="number" min="0" step="any" required></label><label>Total invertido<input id="total" readonly></label></div><p id="referenciaPrecio" class="aviso"></p><label>Fecha de compra<input id="fecha" type="date" required></label><p id="error" class="error" role="alert"></p><button id="guardarCompra" class="comprar" type="submit">Agregar al portfolio</button></form></dialog>
<dialog id="modalVenta"><form id="formVenta"><div class="modalTitulo"><h2>Vender instrumento</h2><button type="button" id="cerrarModalVenta" class="cerrar">×</button></div><label>Instrumento en cartera<select id="instrumentoVenta" required><option value="">Seleccioná un instrumento…</option></select></label><div class="dos"><label>Ticker<input id="tickerVenta" readonly></label><label>Cantidad <button type="button" id="venderTodo" class="todo">Vender todo</button><input id="cantidadVenta" type="number" min="0" step="any" required></label></div><div class="dos"><label>Precio por unidad <span id="monedaVenta"></span><input id="precioVenta" type="number" min="0" step="any" required></label><label>Total a recibir<input id="totalVenta" readonly></label></div><label>Fecha de venta<input id="fechaVenta" type="date" required></label><p id="errorVenta" class="error" role="alert"></p><button id="guardarVenta" class="vender-submit" type="submit">Vender del portfolio</button></form></dialog>
<script>window.APP_CONTEXT = '<%= request.getContextPath() %>';</script><script src="<%= request.getContextPath() %>/assets/dashboard.js"></script></body></html>
