<%@ page contentType="text/html;charset=UTF-8" %>
<!DOCTYPE html>
<html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>InversorAR</title><link rel="stylesheet" href="<%= request.getContextPath() %>/assets/dashboard.css"></head>
<body><header><div class="brand"><span>✓</span> InversorAR</div><nav>Dashboard　 Portfolio　 Rendimiento　 Historial　 Simulador</nav><div class="acciones"><button id="abrirModal">＋ Comprar</button><button id="abrirModalVenta" class="vender">− Vender</button></div></header>
<main><h1>Mi Portfolio</h1><p class="sub">Resumen del portfolio de demostración</p><section class="metricas"><article><small>CAPITAL INVERTIDO</small><strong id="capital">—</strong></article><article><small>PATRIMONIO TOTAL</small><strong id="patrimonio">—</strong></article><article><small>GANANCIA TOTAL</small><strong id="ganancia">—</strong></article></section>
<section class="panel"><h2>Mis inversiones</h2><div id="posiciones" class="posiciones"><p>Cargando inversiones…</p></div></section></main>
<dialog id="modal"><form id="formCompra"><div class="modalTitulo"><h2>Comprar instrumento</h2><button type="button" id="cerrarModal" class="cerrar">×</button></div><label>Instrumento<select id="instrumento" required><option value="">Seleccioná un instrumento…</option></select></label><div class="dos"><label>Ticker<input id="ticker" readonly></label><label>Cantidad<input id="cantidad" type="number" min="0.000001" step="any" required></label></div><div class="dos"><label>Precio por unidad (USD)<input id="precio" type="number" min="0.0001" step="any" required></label><label>Total invertido (USD)<input id="total" readonly></label></div><label>Fecha de compra<input id="fecha" type="date" required></label><p id="error" class="error" role="alert"></p><button class="comprar" type="submit">Agregar al portfolio</button></form></dialog>
<dialog id="modalVenta"><form id="formVenta"><div class="modalTitulo"><h2>Vender instrumento</h2><button type="button" id="cerrarModalVenta" class="cerrar">×</button></div><label>Instrumento en cartera<select id="instrumentoVenta" required><option value="">Seleccioná un instrumento…</option></select></label><div class="dos"><label>Ticker<input id="tickerVenta" readonly></label><label>Cantidad <button type="button" id="venderTodo" class="todo">Vender todo</button><input id="cantidadVenta" type="number" min="0.000001" step="any" required></label></div><div class="dos"><label>Precio por unidad (USD)<input id="precioVenta" type="number" min="0.0001" step="any" required></label><label>Total a recibir (USD)<input id="totalVenta" readonly></label></div><label>Fecha de venta<input id="fechaVenta" type="date" required></label><p id="errorVenta" class="error" role="alert"></p><button class="vender-submit" type="submit">Vender del portfolio</button></form></dialog>
<script>window.APP_CONTEXT = '<%= request.getContextPath() %>';</script><script src="<%= request.getContextPath() %>/assets/dashboard.js"></script></body></html>
